---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: default
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: homelab
  path: "./clusters/homelab/apps"
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure
