---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: json-resume
  namespace: infrastructure
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/json-resume
      version: "*"
      sourceRef:
        kind: GitRepository
        name: homelab
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    force: true
  dependsOn:
    - name: cert-manager
    - name: traefik
  values:
    # Override values if needed
    ingress:
      host: kragh.dev

    # Increase replicas for better availability
    webServer:
      replicas: 2
