---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: json-resume
  namespace: apps
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/json-resume
      version: '*'
      sourceRef:
        kind: GitRepository
        name: homelab
        namespace: default
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Override values if needed
    ingress:
      host: kragh.dev
    
    # Increase replicas for better availability
    webServer:
      replicas: 2
