---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matter-server
  namespace: apps
spec:
  interval: 15m
  targetNamespace: home-assistant
  releaseName: matter-server
  chart:
    spec:
      chart: ./charts/matter-server
      sourceRef:
        kind: GitRepository
        name: homelab
        namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  # Ensure Matter server waits for Home Assistant to be ready
  dependsOn:
    - name: home-assistant
      namespace: apps
  values:
    # Image configuration
    image:
      repository: ghcr.io/home-assistant-libs/python-matter-server
      tag: "stable"
      pullPolicy: IfNotPresent

    # Ensure deployment on node with USB device
    nodeSelector:
      kubernetes.io/hostname: gigabyte

    # USB device configuration for Zigbee stick
    usbDevice:
      hostPath: /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_25_9B_C8_2C-if00-port0
      containerPath: /dev/ttyUSB0

    # Persistence for Matter server data
    persistence:
      enabled: true
      size: 1Gi
      storageClass: "local-path"
      accessMode: ReadWriteOnce

    # Security context - privileged required for USB access
    securityContext:
      privileged: true

    # Service configuration
    service:
      type: ClusterIP
      port: 5580
      targetPort: 5580

    # Resource limits
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

    # Pod annotations for better observability
    podAnnotations:
      matter-server/usb-device: "zigbee-stick"
