# Default values for matter-server
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: ghcr.io/home-assistant-libs/python-matter-server
  pullPolicy: IfNotPresent
  tag: "stable"

nameOverride: ""
fullnameOverride: ""

# Node selector to ensure deployment on specific node with USB device
nodeSelector:
  kubernetes.io/hostname: gigabyte

# USB device configuration
usbDevice:
  # Path to the USB device on the host
  hostPath: /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_25_9B_C8_2C-if00-port0
  # Mount path inside the container
  containerPath: /dev/ttyUSB0

# Persistence configuration
persistence:
  enabled: true
  size: 1Gi
  storageClass: "local-path"
  accessMode: ReadWriteOnce

# Security context - privileged required for USB device access
securityContext:
  privileged: true

# Service configuration
service:
  type: ClusterIP
  port: 5580
  targetPort: 5580

# Resource limits
resources:
  {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 256Mi

# Environment variables
env: []

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext: {}

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Tolerations
tolerations: []

# Affinity
affinity: {}
