infiscal_client_id: ENC[AES256_GCM,data:o8thU07bYVDMOQQrOij/qUeHZvrzvEyA40k9RVeS5SpgXm2h,iv:ohI22HkOxNa//712FBXk9uqQCsYfnTJPFKHtnenXPB8=,tag:2koBulrhu2lhBYTWagU6cw==,type:str]
infiscal_client_secret: ENC[AES256_GCM,data:ZTNL/3fPgHaNheDP0tG6LtTzrTr4tt4MBDJdvwXQPbwnxja8oUfRfQtwgt9Z5RZiwtSN3cK4EY5EldAo7vStHA==,iv:bcLCC1OoNNX55v7qDx1I6S+rWJ7HgBP/IbTXEMZ6mfE=,tag:IJkdTBcpiOnmAav5/wuS6Q==,type:str]
gigabyte_password: ENC[AES256_GCM,data:Anvd8f77aCweBGh1xhkS8g==,iv:QcLeuoDcZsS66lc3eJZyISbS1utPMGgv24dOYHjkHcM=,tag:WepDD/MkTnHoecY/Tr6RoA==,type:str]
vps1_password: ENC[AES256_GCM,data:B8PrPYFDTHI3ovPlQT/IOQ==,iv:eebLXeVjzNJH8o0r7V3BNrTFsVZ2lp90dn3x7jtdM0E=,tag:y2/1jMG+z6sh1m+cYJEv2A==,type:str]
sops:
    age:
        - recipient: age19cjycc6l8pnjxgmclp7jzfd6kx79v2w3vrn3y9xzhd2hkfmyvvls6jk3v7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRElaS2dwb2srRlhlUkdB
            aFNlQ2V0MGlUcytHeHU0RjdWRit1Y1hVelNrClFreVpXbmROVUdlZ1lUMGJmaXhq
            ZmhFaTdDTXV5RVpmV3ZIQ25nZTZ6U0UKLS0tIEErdFpjR0tUZGdKNDZEdTBMTGFB
            ZkYyU3Bod3NsdFVrN0oxMkw4UWR4cjAKsn0xBJ+npSOEyBWU9Ir92CNujBaJGt+W
            JN82qmN7A2mmFtbQCsWg2BC8MkGfFJKUDWQomLTYknP5csHddUa5zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T20:46:37Z"
    mac: ENC[AES256_GCM,data:tXEcli9kk/27H0bbJcN18+CAKHuD6tolMNKvo8BfK/HmzqmS0iSNw8ZkbkSp5AMTiwYZwlGN6wppK6r7GmDvW31xX0PEZhMy6bZaB/x+w83Ra668sLkXyWrW17uWTd2Tj1rus6OPYLE0JNhY9Ccj0Emea+g77bC0X+SvdFlXi7o=,iv:ClyAfizE52n7eZbijbevWO8kWcOOoLs8MIMyYlNx4NE=,tag:eyip/2NMwcWAwjJkD7t6xg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
