---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 15m
  releaseName: external-secrets
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: "0.19.2"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  dependsOn:
    - name: infrastructure-external-secrets-config
  values:
    # Enable all controllers
    installCRDs: true

    # Enable Bitwarden SDK Server for Bitwarden Secrets Manager
    bitwarden-sdk-server:
      enabled: true
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault

    # Resource settings
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

    # Security context
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      capabilities:
        drop:
          - ALL

    # Service monitor for Prometheus (optional)
    serviceMonitor:
      enabled: false

    # Webhook configuration
    webhook:
      create: true
      port: 9443

    # Cert controller for webhook certificates
    certController:
      create: true
