---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # First create the namespace
  - namespace.yaml
  # Then the infrastructure components
  - cert-manager.yaml
  - external-secrets.yaml
  - traefik.yaml
  - infrastructure-config.yaml
  - infrastructure-external-secrets-config.yaml
  # Skip external-dns for now if it's commented out
  # - external-dns.yaml
