---
# k3s-edge-node role: Configure VPS as k3s agent node for public ingress
# 
# This role sets up the VPS as a k3s agent node that:
# 1. Joins the existing k3s cluster via Tailscale
# 2. Has node labels for Traefik ingress controller affinity
# 3. Allows external traffic on ports 80/443

- name: Get k3s server host from inventory
  set_fact:
    k3s_server_host: "{{ groups['k3s_server'][0] }}"

- name: Get k3s server Tailscale IP
  command: tailscale status --json
  register: tailscale_status
  delegate_to: "{{ k3s_server_host }}"
  
- name: Parse Tailscale status to get server IP
  set_fact:
    k3s_server_tailscale_ip: "{{ (tailscale_status.stdout | from_json).Self.TailscaleIPs[0] }}"

- name: Get k3s node token from server
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token_file
  delegate_to: "{{ k3s_server_host }}"
  become: true

- name: Set k3s token fact
  set_fact:
    k3s_token: "{{ k3s_token_file.content | b64decode | trim }}"

- name: Get current edge node Tailscale IP
  command: tailscale status --json
  register: edge_tailscale_status
  
- name: Parse edge Tailscale status to get current host IP
  set_fact:
    current_tailscale_ip: "{{ (edge_tailscale_status.stdout | from_json).Self.TailscaleIPs[0] }}"

- name: Download k3s installer
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Install k3s as agent
  environment:
    K3S_URL: "https://{{ k3s_server_tailscale_ip }}:6443"
    K3S_TOKEN: "{{ k3s_token }}"
    INSTALL_K3S_EXEC: >
      agent
      --node-label edge=true
      --node-label node.kubernetes.io/edge=true
      --node-external-ip {{ ansible_default_ipv4.address }}
      --flannel-iface tailscale0
      --node-ip {{ current_tailscale_ip }}
  shell: /tmp/k3s-install.sh
  args:
    creates: /usr/local/bin/k3s-agent

- name: Start and enable k3s-agent
  systemd:
    name: k3s-agent
    state: started
    enabled: true

- name: Wait for node to join cluster
  pause:
    seconds: 30

- name: Install iptables-persistent for rule persistence
  package:
    name: iptables-persistent
    state: present

- name: Configure iptables to allow external traffic to k3s
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    comment: "Allow external access to k3s ingress"
  loop:
    - "80"
    - "443"
    - "30080"  # NodePort for web
    - "30443"  # NodePort for websecure
    - "6443"   # k3s API if needed

- name: Configure iptables port forwarding for Traefik ingress
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: "{{ item.src }}"
    jump: REDIRECT
    to_ports: "{{ item.dst }}"
    comment: "Forward port {{ item.src }} to {{ item.dst }} for Traefik"
  loop:
    - { src: "80", dst: "30080" }
    - { src: "443", dst: "30443" }

- name: Save iptables rules
  shell: iptables-save > /etc/iptables/rules.v4
  notify: restart iptables-persistent
