---
# k3s-edge-node role: Configure VPS as k3s agent node for public ingress
# 
# This role sets up the VPS as a k3s agent node that:
# 1. Joins the existing k3s cluster via Tailscale
# 2. Has node labels for Traefik ingress controller affinity
# 3. Allows external traffic on ports 80/443
#
# Required variables (passed from playbook):
# - k3s_server_hostname: hostname of the k3s server
# - k3s_token: k3s node token for joining the cluster

- name: Get current edge node Tailscale IP
  command: tailscale status --json
  register: edge_tailscale_status
  
- name: Parse edge Tailscale status to get current host IP
  set_fact:
    current_tailscale_ip: "{{ (edge_tailscale_status.stdout | from_json).Self.TailscaleIPs[0] }}"

- name: Download k3s installer
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Install k3s as agent
  environment:
    K3S_URL: "https://{{ k3s_server_hostname }}:6443"
    K3S_TOKEN: "{{ k3s_token }}"
    INSTALL_K3S_EXEC: >
      agent
      --node-label edge=true
      --node-label node.kubernetes.io/edge=true
      --node-external-ip {{ ansible_default_ipv4.address }}
      --flannel-iface tailscale0
      --node-ip {{ current_tailscale_ip }}
  shell: /tmp/k3s-install.sh
  args:
    creates: /usr/local/bin/k3s-agent

- name: Start and enable k3s-agent
  systemd:
    name: k3s-agent
    state: started
    enabled: true

- name: Wait for node to join cluster
  pause:
    seconds: 30

- name: Apply taint to edge node to prevent regular workloads
  command: >
    kubectl taint nodes {{ inventory_hostname }} 
    edge=true:NoSchedule --overwrite
  delegate_to: "{{ k3s_server_hostname }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  become: true

- name: Install iptables-persistent for rule persistence
  package:
    name: iptables-persistent
    state: present

- name: Configure iptables to allow external traffic to k3s
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    comment: "Allow external access to k3s ingress"
  loop:
    - "80"
    - "443"
    - "30080"  # NodePort for web
    - "30443"  # NodePort for websecure
    - "6443"   # k3s API if needed

- name: Allow traffic from Tailscale interface to k3s services
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    comment: "Allow Tailscale access to k3s services"
    in_interface: "tailscale0"
  loop:
    - "80"
    - "443"
    - "30080"
    - "30443"

- name: Configure iptables port forwarding for Traefik ingress (public interface)
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: "{{ item.src }}"
    jump: REDIRECT
    to_ports: "{{ item.dst }}"
    comment: "Forward port {{ item.src }} to {{ item.dst }} for Traefik"
    in_interface: "!tailscale0"  # Only for non-Tailscale traffic
  loop:
    - { src: "80", dst: "30080" }
    - { src: "443", dst: "30443" }

- name: Configure iptables port forwarding for Traefik ingress (Tailscale interface)
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: "{{ item.src }}"
    jump: REDIRECT
    to_ports: "{{ item.dst }}"
    comment: "Forward port {{ item.src }} to {{ item.dst }} for Traefik (Tailscale)"
    in_interface: "tailscale0"
  loop:
    - { src: "80", dst: "30080" }
    - { src: "443", dst: "30443" }

- name: Save iptables rules
  shell: iptables-save > /etc/iptables/rules.v4
  notify: restart iptables-persistent
