apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nanobot-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nanobot-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        config.json: |
          {
            "providers": {
              "openai": {
                "apiKey": "{{ .NANOBOT_API_KEY }}",
                "apiBase": "https://ollama.com"
              }
            },
            "agents": {
              "defaults": {
                "model": "gpt-oss:20b-cloud"
              }
            },
            "tools": {
              "restrictToWorkspace": true
            }
          }
  data:
    - secretKey: NANOBOT_API_KEY
      remoteRef:
        key: NANOBOT_API_KEY