apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nanobot
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nanobot.kragh.dev`)
      kind: Rule
      services:
        - name: nanobot-assistant
          port: 18790
      middlewares:
        - name: oidc
          namespace: traefik
  tls:
    secretName: nanobot-kragh-dev-tls