---
apiVersion: v1
kind: Secret
metadata:
    name: nanobot-secrets
    namespace: apps
stringData:
    config.json: ENC[AES256_GCM,data:PepwABiep0A5mK/Wi3sCyiHUvZ4rKk0aj+h0HLetPNG6Z/mBhUOfbiEYGsBE1v5BghmS3Zf7aKO7dWROx1A+WZtSka5kQJteInUR4oTwaZ2cULXqs5ArKW1PwCJ6GW2LREyZAJeRJUcU00uk89YAg6WFoJXCQ476DCsA8RhMRstGIVVR363l3dSsP9iLfxDk0HsyKtTS3upreC2w2fp0du2Mj1TGZSwgYUwNMUCCnl7uCI9xeSOMldk9uqXTCf3I+231Y0nwu2aDX7m3cQK9tSOlhb2OJwn/Ku8XtB/R0CJp4kErweMYcCR9AfDHMJvUqLqTC/4xLjmCHXJ0vb8AGOCn/9Bcum+SkQBCfk0kv/d1T04/mZtm96dzpWBfUQHwx2Y=,iv:l2dXYOAe5faSRpNs6s9mZjrfwoVHq8YoqwrCKalrHOA=,tag:8IccgQ6bvK6O9jVw4fKy4Q==,type:str]
sops:
    age:
        - recipient: age19cjycc6l8pnjxgmclp7jzfd6kx79v2w3vrn3y9xzhd2hkfmyvvls6jk3v7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNU5CaUppSktrZU01VjdD
            dFhUbXNUVTc4alFWNFpsQnZNRERRZkEyV1V3Cm5ERGRNK1VPNkJvRVduUEdSMmtH
            ckx0V3owd3kyVmhzWmcrM2ppVWJrcW8KLS0tIE5jNElXTEVBTHBRd0lRRjI3eXhm
            Q1JjMjUrcnNlUFIrcUUwKzZaY1VUL2sKhQXOjsEeqJWtd3pPhHLMIA/FNcgz9qy1
            NBBXXxKy4lgxydtx5yZuxgNlE1kT1QDsuIrFEu4ZxRIKA+HHdyYsug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T00:38:10Z"
    mac: ENC[AES256_GCM,data:PErzGcoM2iNM+q0iDKVtXIanv5trKavfCB9bCSRJugWVfwBQX6lZ9pNhWCeXym0XlI2xJyQUGz+vayh0v1WttfGiswuXzjEKTCZj/NOXKXRrEMi/Lgl5ehJTmFU/PEzLu27V1+dQ4EmKWmB8aw/yZSBIwp6I3IGB4h5xj62FNz8=,iv:GC7EvsPr6D4Z74VKnxVJYtvuKmSWevb9xjIXt8YAHYA=,tag:9u6DmmnF1YnxszMavX6Qlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
