---
# Self-signed ClusterIssuer for internal certificates
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bitwarden-selfsigned-issuer
spec:
  selfSigned: {}
---
# Certificate for Bitwarden SDK Server TLS
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-sdk-server-tls
  namespace: external-secrets
spec:
  secretName: bitwarden-tls-certs
  issuerRef:
    name: bitwarden-selfsigned-issuer
    kind: ClusterIssuer
  commonName: bitwarden-sdk-server.external-secrets.svc.cluster.local
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
    - bitwarden-sdk-server.external-secrets.svc
    - bitwarden-sdk-server
    - localhost
