---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            namespace: default
            name: infiscal-universal-auth-credentials
            key: cinfiscal_client_idd
          clientSecret:
            namespace: default
            name: infiscal-universal-auth-credentials
            key: infiscal_client_secret
      secretsScope:
        projectSlug: homelab
        environmentSlug: live