# SOPS configuration: define which files get encrypted and recipients
creation_rules:
  - path_regex: ansible/secrets/.*\.ya?ml
    age: age19cjycc6l8pnjxgmclp7jzfd6kx79v2w3vrn3y9xzhd2hkfmyvvls6jk3v7
