---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: desec-token
  namespace: tailscale
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: desec-token
  data:
  - secretKey: token
    remoteRef:
      key: desec-token