---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: desec-token
  namespace: external-dns
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: desec-token
  data:
  - secretKey: token
    remoteRef:
      key: DESEC_TOKEN
