---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hetzner-token
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: hetzner-token
  data:
  - secretKey: token
    remoteRef:
      key: HETZNER_TOKEN
