{{- if .Values.litellm.enabled }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: litellm
  namespace: apps
spec:
  type: "oci"
  interval: 24h
  url: oci://ghcr.io/berriai
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: litellm-helm
      version: "1.82.3"
      sourceRef:
        kind: HelmRepository
        name: litellm
        namespace: apps
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: -1
  values:
    environmentSecrets:
      - litellm-secrets
    proxy_config:
      model_list:
        # dummy model to start proxy
        - model_name: "llama-default"
          litellm_params:
            model: ollama/llama3.2
            api_base: os.environ/OLLAMA_API_BASE
      general_settings:
        allow_unknown_models: true
        master_key: os.environ/LITELLM_MASTER_KEY # Your admin key
        max_budget: 20.0 # Safety cap: LiteLLM will stop cloud requests at $20/mo
        budget_duration: 30d
        # Allows usage of the UI at https://litellm.kragh.dev/ui
        ui_access_mode: "admin"
    extraEnv:
      - name: OPENROUTER_API_KEY
        valueFrom:
          secretKeyRef:
            name: litellm-secrets
            key: OPENROUTER_API_KEY
      - name: OLLAMA_API_BASE
        value: "http://ollama-service.ollama-namespace.svc.cluster.local:11434"
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: litellm.kragh.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: litellm-tls
          hosts:
            - litellm.kragh.dev
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical 
    kind: ClusterSecretStore
  target:
    name: litellm-secret
    creationPolicy: Owner
  data:
    - secretKey: OPENROUTER_API_KEY
      remoteRef:
        key: OPENROUTER-API-KEY
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: LITELLM-MASTER-KEY
{{- end }}
