{{- if .Values.matterIntegration.enabled }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matter-integration
  namespace: apps
spec:
  interval: 15m
  targetNamespace: home-assistant
  releaseName: matter-integration
  chart:
    spec:
      chart: ./charts/matter-integration
      version: "*"
      sourceRef:
        kind: GitRepository
        name: homelab
        namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    force: true
    remediation:
      retries: 3
  dependsOn:
    - name: home-assistant
      namespace: apps
{{- end }}