apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-openclaw
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/my-openclaw
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: homelab
        namespace: default
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  values:
    ingress:
      host: oidc.kragh.dev
    service:
      type: ClusterIP
      port: 80
    image:
      repository: ghcr.io/<username>/openclaw
      tag: latest
    replicas: 1
