---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: open-webui
  namespace: infrastructure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`open-webui.kragh.dev`)
      kind: Rule
      services:
        - name: oauth2-proxy
          port: 80
          nativeLB: true
  tls:
    secretName: open-webui-tls