{{- if .Values.zigbee2mqtt.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: zigbee2mqtt
    namespace: flux-system
spec:
    interval: 10m
    url: https://charts.zigbee2mqtt.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: zigbee2mqtt
    namespace: flux-system
spec:
    interval: 5m
  targetNamespace: home-assistant
  releaseName: zigbee2mqtt
    chart:
        spec:
            chart: zigbee2mqtt
            version: '1.37.1'
            sourceRef:
                kind: HelmRepository
                name: zigbee2mqtt
                namespace: flux-system
            interval: 10m
{{- end }}