---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 15m
  targetNamespace: home-assistant
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: home-assistant
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Configure options applied to all pods
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      # Configure the main controller
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          # Configure the main application container
          main:
            image:
              # Official Home Assistant image
              repository: ghcr.io/home-assistant/home-assistant
              # Latest stable version
              tag: "2025.9.1"

            resources:
              limits:
                cpu: 2000m
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 512Mi

            env:
              TZ: "UTC"
              # Disable privileged mode for security
              HASS_SERVER_HOST: "0.0.0.0"

            probes:
              liveness:
                enabled: true
                spec:
                  httpGet:
                    path: /api/
                    port: 8123
                  initialDelaySeconds: 60
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 3

              readiness:
                enabled: true
                spec:
                  httpGet:
                    path: /api/
                    port: 8123
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3

    service:
      # Configure a service for the main application
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8123

    ingress:
      # Configure an Ingress for the main application
      main:
        hosts:
          - host: &host "home.kragh.dev"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: home-assistant-tls

    persistence:
      # Configure the main configuration storage location
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: "local-path"
        globalMounts:
          - path: /config

      # Configure HTTP settings for reverse proxy support
      http-config:
        type: configMap
        name: home-assistant-http-config
        globalMounts:
          - path: /config/http.yaml
            subPath: http.yaml

      # Configure temporary storage for logs
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp

    configMaps:
      home-assistant-http-config:
        enabled: true
        data:
          http.yaml: |
            # HTTP Configuration for Home Assistant
            # This file configures trusted proxies for reverse proxy support
            http:
              use_x_forwarded_for: true
              trusted_proxies:
                - 10.42.0.0/16    # k3s pod network
                - 10.43.0.0/16    # k3s service network  
                - 172.16.0.0/12   # Docker default bridge networks
                - 192.168.0.0/16  # Private networks
                - 127.0.0.1       # Localhost
