---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: external-dns
  chart:
    spec:
      chart: external-dns
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Global settings
    interval: 1m
    logLevel: info
    logFormat: text

    # DNS provider - Hetzner DNS
    provider: hetzner
    env:
      - name: HETZNER_TOKEN
        valueFrom:
          secretKeyRef:
            name: hetzner-dns-token
            key: token
    #         key: access-key-id
    #   - name: AWS_SECRET_ACCESS_KEY
    #     valueFrom:
    #       secretKeyRef:
    #         name: aws-credentials
    #         key: secret-access-key

    # For Google Cloud DNS:
    # provider: google
    # env:
    #   - name: GOOGLE_APPLICATION_CREDENTIALS
    #     value: /etc/secrets/service-account/credentials.json
    # extraVolumes:
    #   - name: google-service-account
    #     secret:
    #       secretName: google-service-account
    # extraVolumeMounts:
    #   - name: google-service-account
    #     mountPath: /etc/secrets/service-account
    #     readOnly: true

    # Domain filtering
    domainFilters:
      - kragh.dev # Only manage records for this domain

    # Sources to monitor for DNS records
    sources:
      - ingress
      - service # For LoadBalancer services

    # Policy for existing records
    policy: upsert-only # Only create/update, never delete

    # Registry for tracking managed records
    registry: txt
    txtOwnerId: external-dns-homelab
    txtPrefix: external-dns-

    # Resource settings
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

    # RBAC
    rbac:
      create: true
      additionalPermissions:
        - apiGroups: [""]
          resources: ["endpoints"]
          verbs: ["get", "watch", "list"]

    # Service account
    serviceAccount:
      create: true
      annotations: {}

    # Security context
    securityContext:
      fsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
