---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["helm.toolkit.fluxcd.io"]
  resources: ["helmreleases"]
  verbs: ["get", "watch", "list"]
