---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: suwayomi-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: suwayomi-secrets
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: ADMIN_PASSWORD

