---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suwayomi-data
  labels:
    app.kubernetes.io/name: suwayomi
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
