---
apiVersion: v1
kind: Service
metadata:
  name: suwayomi
  labels:
    app.kubernetes.io/name: suwayomi
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: suwayomi
  ports:
    - port: 80
      targetPort: 4567
      protocol: TCP
      name: http
