---
# Default variables for edge_gateway role
edge_gateway_wireguard_port: 51820
edge_gateway_wg_local: 10.172.90.2
edge_gateway_wg_peer: 10.172.90.1
edge_gateway_wg_peer_public_key: "s8uvfVm8iM6yigJR2OuoVN3A4mCs5iWhkQIKlhLf1Ck="
edge_gateway_wg_peer_endpoint: "wg.kragh.dev:51820"
edge_gateway_cluster_cidr: 192.168.50.0/24
# Traefik backend target (now using WireGuard peer node IP instead of previous VIP 192.168.50.240)
edge_gateway_traefik_vip: "{{ edge_gateway_wg_peer }}"
edge_gateway_ingress_ports:
  - 80
  - 443
edge_gateway_enable_healthcheck: true
# Deprecated: cron style string was invalid for systemd OnCalendar
edge_gateway_healthcheck_interval: "*/2 * * * *"  # deprecated, unused
# New: minutes between health checks (monotonic timer)
edge_gateway_healthcheck_interval_minutes: 2
# Set to false after first deploy if you manage keys manually
edge_gateway_generate_wg_key: true
# Provide via vaulted variable if generate is false: edge_gateway_wg_private_key

# New: operating mode for handling inbound HTTP(S)
#   proxy  - (Option B) L4 proxy with PROXY protocol via HAProxy (preserves client IP)
#   dnat   - (Original) DNAT forward (requires symmetric routing or SNAT) [NOT USED NOW]
edge_gateway_mode: proxy

# HAProxy specific settings (effective when edge_gateway_mode == 'proxy')
edge_gateway_enable_haproxy: true
edge_gateway_haproxy_user: haproxy
edge_gateway_haproxy_group: haproxy
edge_gateway_haproxy_maxconn: 2000
edge_gateway_haproxy_timeout_client: 60s
edge_gateway_haproxy_timeout_server: 60s
edge_gateway_haproxy_timeout_connect: 5s
# Backend now points to Traefik NodePorts (set in HelmRelease). Frontend still listens 80/443.
edge_gateway_proxy_backend_http_port: 30080
edge_gateway_proxy_backend_https_port: 30443
# Trusted source IPs for Traefik proxyProtocol (documented for cluster side)
edge_gateway_proxy_trusted_source_ips:
  - "{{ edge_gateway_wg_local }}"
# Optional: add public IP if Traefik will also trust it (example placeholder)
#  - "<edge-public-ip>"
