---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-github-oauth
  namespace: dex
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: dex-github-oauth
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        config.yaml: |
          issuer: https://dex.kragh.dev
          storage:
            type: kubernetes
            config:
              inCluster: true

          oauth2:
            responseTypes: ["code", "token", "id_token"]
            skipApprovalScreen: true

          connectors:
            - type: github
              id: github
              name: GitHub
              config:
                clientID: "{{ `{{ .github_client_id }}` }}"
                clientSecret: "{{ `{{ .github_client_secret }}` }}"
                redirectURI: https://dex.kragh.dev/callback
                orgs:
                  - name: tonur

          staticClients:
            - id: kubernetes
              name: Kubernetes
              redirectURIs:
                - http://localhost:8000
                - http://localhost:18000
              secret: some-long-secret-string
  data:
    - secretKey: github_client_id
      remoteRef:
        key: dex-github-oauth-client-id
    - secretKey: github_client_secret
      remoteRef:
        key: dex-github-oauth-client-secret