---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-helmrepo.yaml
  - cert-manager-helmrelease.yaml
  - external-secrets-helmrepo.yaml
  - external-secrets-helmrelease.yaml
