---
- name: restart wireguard
  systemd:
    name: wg-quick@wg0
    state: restarted

- name: reload nftables
  systemd:
    name: nftables
    state: restarted

- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted

- name: reload haproxy
  systemd:
    name: haproxy
    state: reloaded
