---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-resume
  namespace: json-resume
  labels:
    app: json-resume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: json-resume
  template:
    metadata:
      labels:
        app: json-resume
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: generated-html
          mountPath: /usr/share/nginx/html
          readOnly: true
        livenessProbe:
          httpGet:
            path: /index.html
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /index.html
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: generated-html
        persistentVolumeClaim:
          claimName: resume-html-pvc
