---
apiVersion: batch/v1
kind: Job
metadata:
  name: resume-builder
  namespace: json-resume
spec:
  template:
    metadata:
      labels:
        app: resume-builder
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      - name: install-resume-cli
        image: node:20-alpine
        command:
        - sh
        - -c
        - |
          npm install -g resume-cli
          cp -r /usr/local/lib/node_modules /shared/
          cp -r /usr/local/bin /shared/
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: shared-tools
          mountPath: /shared
        - name: tmp
          mountPath: /tmp
      containers:
      - name: build-resume
        image: node:20-alpine
        command:
        - sh
        - -c
        - |
          export PATH="/shared/bin:$PATH"
          export NODE_PATH="/shared/lib/node_modules"
          cd /workspace
          resume export index.html --resume resume.json --theme even
          echo "Resume built successfully"
          ls -la /workspace/
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: resume-data
          mountPath: /workspace/resume.json
          subPath: resume.json
          readOnly: true
        - name: generated-html
          mountPath: /workspace
        - name: shared-tools
          mountPath: /shared
          readOnly: true
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: resume-data
        configMap:
          name: resume-data
      - name: generated-html
        persistentVolumeClaim:
          claimName: resume-html-pvc
      - name: shared-tools
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-html-pvc
  namespace: json-resume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
