---
apiVersion: v1
kind: Service
metadata:
  name: json-resume
  namespace: json-resume
  labels:
    app: json-resume
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: http
spec:
  selector:
    app: json-resume
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
