---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/homelab/infrastructure/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  timeout: 5m
  wait: true
  dependsOn:
    - name: infrastructure-base
  # Wait for External Secrets Operator and cert-manager to be ready
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: external-secrets
      namespace: external-secrets
