---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-base
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/homelab/infrastructure/base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  timeout: 5m
  wait: true
