# Values for homeassistant-config chart
# This chart provides additional configuration resources for Home Assistant

homeAssistant:
  # Domain name for Home Assistant
  hostname: "home.kragh.dev"
  # Target IP for DNS records
  targetIP: "198.55.102.244"
  # Namespace where Home Assistant is deployed
  namespace: "home-assistant"

# HTTP Configuration
httpConfig:
  enabled: true
  trustedProxies:
    - "10.42.0.0/16"    # k3s pod network
    - "10.43.0.0/16"    # k3s service network  
    - "172.16.0.0/12"   # Docker default bridge networks
    - "192.168.0.0/16"  # Private networks
    - "127.0.0.1"       # Localhost

# DNS Configuration
dnsEndpoint:
  enabled: true
  ttl: 300