---
# k3s-control-plane role: Install and configure Kubernetes control plane
# 
# This role sets up the k3s server (control plane) with:
# - Disabled built-in Traefik (we deploy our own via Flux)
# - Node token generation for worker nodes to join

- name: Download k3s installer
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Install k3s control plane
  environment:
    INSTALL_K3S_EXEC: "--disable traefik"
  shell: /tmp/k3s-install.sh
  args:
    creates: /usr/local/bin/k3s

- name: Wait for kubeconfig
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    timeout: 120

- name: Read node token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Set fact for node token
  set_fact:
    k3s_node_token: "{{ node_token.content | b64decode | trim }}"
