---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio
  namespace: stremio-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: stremio
        image: "stremio/server:latest"
        ports:
        - containerPort: 11470
          name: http
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 400m
            memory: 2Gi
        livenessProbe:
          tcpSocket:
            port: 11470
        readinessProbe:
          tcpSocket:
            port: 11470
