apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  labels:
    app: matter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      serviceAccountName: matter-integration
      nodeSelector:
        kubernetes.io/hostname: gigabyte
      containers:
        - name: matter-server
          image: "{{ .Values.matterServer.image.repository }}:{{ .Values.matterServer.image.tag }}"
          ports:
            - name: matter-api
              containerPort: 5580
          env:
            # Point Matter Server to OTBR service
            - name: OTBR_AGENT_URL
              value: "spinel+tcp://otbr:49191"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.matterServer.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: matter-server-data