apiVersion: v1
kind: Service
metadata:
  name: matter-server
  labels:
    app: matter-server
spec:
  type: ClusterIP
  ports:
    - port: 5580
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: matter-server