apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-data
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: matter-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path