---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio-service
  namespace: stremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stremio-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stremio-service
    spec:
      containers:
      - name: stremio
        image: "stremio/server:latest"
        ports:
        - containerPort: 11470
          name: http
        - containerPort: 12470
          name: https
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 400m
            memory: 2Gi
        livenessProbe:
          tcpSocket:
            port: 11470
        readinessProbe:
          tcpSocket:
            port: 11470
