---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stremio-service-tailscale
  namespace: stremio
spec:
  ingressClassName: traefik
  rules:
    - host: homelab.pirate-acrux.ts.net
      http:
        paths:
          - path: /stremio
            pathType: Prefix
            backend:
              service:
                name: stremio-service
                port:
                  number: 11470