# Default values for json-resume
# This is a YAML-formatted file.

# Application configuration
app:
  name: json-resume
  namespace: json-resume

# Resume data
resume:
  # The resume.json content will be templated
  data: |
    # This will be replaced by the actual resume.json content

# Web server configuration
webServer:
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  
  replicas: 1
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Resume builder job configuration  
resumeBuilder:
  image:
    repository: node
    tag: "24-alpine"
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Storage configuration
storage:
  size: 1Gi
  accessMode: ReadWriteOnce

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Ingress configuration
ingress:
  enabled: true
  host: resume.kragh.dev
  
# Certificate configuration  
certificate:
  enabled: true
  issuer: letsencrypt-prod
