---
# External Secret for Tailscale OAuth credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: operator-oauth
  data:
  - secretKey: clientId
    remoteRef:
      key: tailscale-operator-client-id
  - secretKey: clientSecret
    remoteRef:
      key: tailscale-operator-client-secret