---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: operator-oauth
  data:
  - secretKey: client_id
    remoteRef:
      key: TAILSCALE-OPERATOR-CLIENT-ID
  - secretKey: client_secret
    remoteRef:
      key: TAILSCALE-OPERATOR-CLIENT-SECRET
