apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:WsoHRQdOfE2A4NlJ9DKfOeE=,iv:/bZZW4cKGp/7+O5hUuBS2AMKeTnRlFJKX+NcjTrKm4k=,tag:FHneH3HYxNPPRgDftIpbyg==,type:str]
    client_secret: ENC[AES256_GCM,data:EVqeWJyr4pR5d5kLLxDKGLirWMjX3HSp+8EPEgKBqNlxseGIwhLZ8ciIrw0cqrjQ3E2GqSgEhN9JTuPrMKF7,iv:pHrDsy158cwL9Wy69uLj+A6aJdqqPySXAov04aWdUzI=,tag:EMw1ZJ0fVQkwVm3u3M76nw==,type:str]
sops:
    age:
        - recipient: age19cjycc6l8pnjxgmclp7jzfd6kx79v2w3vrn3y9xzhd2hkfmyvvls6jk3v7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSXI3VW5XcEhiZXovRzNt
            MWhBTXp3ejhUcEZUcmFXYTJyblVhMzY1TjFRCmt6dTVtTzI4QWl4enA2TSsvUURT
            VDVrVHFJbmgvVWpCb2Q1SVhsWmZPNVEKLS0tIEVtWW5QRVV4cWR5VHFYN0c5Z095
            MWdmZnRDZTRJN2xTclArNHlPMWZoQTAKLaRgfDUvZ/+v5OD66KwJOVdjltjA57x7
            pcC7rLsy3aImyCyqyPm+UnvWX2XbcgAqa1F0cq3rPnat5njdZ+I8Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T00:34:53Z"
    mac: ENC[AES256_GCM,data:Xl6WIfy9UvH6Ro7NQdszDgCIFdxsy/l8sDJKLboj1TyhU5vJ3aZ3mpi7493IVjva2fX08yID8oYZfeSSqjqyKtbm7Al0nISh+cOrHaM6H7A5zeucrHo50JSGwPFql6tbF6eYyFet6XfBRgpZSX2d6IRnkBuRB96VMN6DAJK/zLU=,iv:rfqRTgESEYTEwrPys6vvL4d1G9nGGDYCYzBfPaZNtHU=,tag:iE63bimyv7om8R/TpbdvTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
