{{- if .Values.ingress.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ .Values.app.name }}
          port: {{ .Values.service.port }}
          nativeLB: true # Force service-based load balancing (uses service VIP instead of pod IPs)
          strategy: RoundRobin
  tls:
    secretName: {{ .Values.app.name }}-tls
{{- end }}
