---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: json-resume-npm-tools
  namespace: json-resume
  labels:
    app.kubernetes.io/name: json-resume
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.npmTools.storage | default "1Gi" }}
  {{- if .Values.npmTools.storageClass }}
  storageClassName: {{ .Values.npmTools.storageClass }}
  {{- end }}