---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: json-resume-npm-tools
  namespace: json-resume
  labels:
    app.kubernetes.io/name: json-resume
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi