---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.app.name }}-builder-{{ .Files.Get "json-resume.json" | sha256sum | trunc 8 }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: builder
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: builder
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: install-resume-cli
          image: "{{ .Values.resumeBuilder.image.repository }}:{{ .Values.resumeBuilder.image.tag }}"
          imagePullPolicy: {{ .Values.resumeBuilder.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              cd /tmp
              npm install resume-cli
              cp -r node_modules /shared/
              echo '#!/bin/sh' > /shared/resume
              echo 'cd /workspace && /shared/node_modules/.bin/resume "$@"' >> /shared/resume
              chmod +x /shared/resume
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: shared-tools
              mountPath: /shared
            - name: tmp
              mountPath: /tmp
      containers:
        - name: build-resume
          image: "{{ .Values.resumeBuilder.image.repository }}:{{ .Values.resumeBuilder.image.tag }}"
          imagePullPolicy: {{ .Values.resumeBuilder.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              cd /workspace
              ls -la /shared/ || echo "No shared directory"
              NODE_PATH=/shared/node_modules /shared/resume export index.html --resume resume.json
              echo "Resume built successfully"
              ls -la /workspace/
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: resume-data
              mountPath: /workspace/resume.json
              subPath: resume.json
              readOnly: true
            - name: generated-html
              mountPath: /workspace
            - name: shared-tools
              mountPath: /shared
              readOnly: true
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.resumeBuilder.resources | nindent 12 }}
      volumes:
        - name: resume-data
          configMap:
            name: {{ .Values.app.name }}-data
        - name: generated-html
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-html-pvc
        - name: shared-tools
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-html-pvc
  namespace: {{ .Values.app.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
