---
apiVersion: v1
kind: Service
metadata:
  name: json-resume
  namespace: json-resume
  labels:
    app.kubernetes.io/name: json-resume
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: json-resume
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
