apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: home-assistant-dns
  namespace: home-assistant
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "home.kragh.dev"
spec:
  endpoints:
    - dnsName: home.kragh.dev
      recordTTL: 300
      recordType: A
      targets:
        - 198.55.102.244
