# Apps configuration
apps:
  enabled: true

# Application toggles
homeAssistant:
  enabled: true

jsonResume:
  enabled: true

gameservers:
  enabled: true

litellm:
  enabled: true

ollama:
  enabled: true

openWebUI:
  enabled: true

suwayomi:
  enabled: true
