---
# k3s-node-scheduling role: Configure node scheduling strategy
# 
# Simple strategy:
# - gigabyte: Default node (no taint) - ALL workloads go here by default
# - beelink: Tainted for media-only (requires toleration)
# - vhs-vps: Tainted for edge-only (requires toleration)

- name: Fetch kubeconfig from k3s server
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /tmp/k3s-kubeconfig.yaml
    flat: yes
  run_once: true

- name: Fix kubeconfig server URL
  replace:
    path: /tmp/k3s-kubeconfig.yaml
    regexp: 'https://127\.0\.0\.1:6443'
    replace: 'https://{{ hostvars[groups["k3s_control_plane"][0]]["ansible_host"] }}:6443'
  delegate_to: localhost
  run_once: true

- name: Set localhost kubeconfig environment
  set_fact:
    kubeconfig_env:
      KUBECONFIG: /tmp/k3s-kubeconfig.yaml
  run_once: true

# Configure gigabyte as the default compute node (no taint)
- name: Label gigabyte as default compute node
  shell: |
    kubectl label node gigabyte node.homelab.dev/role=compute node.homelab.dev/default=true --overwrite
  delegate_to: localhost
  run_once: true
  environment: "{{ kubeconfig_env }}"

# Configure beelink for media workloads only
- name: Configure beelink as media-only node
  shell: |
    kubectl label node beelink node.homelab.dev/role=media --overwrite
    kubectl taint node beelink node.homelab.dev/media-only=true:NoSchedule --overwrite
  delegate_to: localhost
  run_once: true
  environment: "{{ kubeconfig_env }}"

# Configure vhs-vps for edge/ingress workloads only
- name: Configure vhs-vps as edge-only node
  shell: |
    kubectl label node vhs-vps node.homelab.dev/role=edge node.kubernetes.io/edge=true --overwrite
    kubectl taint node vhs-vps node.homelab.dev/edge-only=true:NoSchedule --overwrite
  delegate_to: localhost
  run_once: true
  environment: "{{ kubeconfig_env }}"

- name: Display node scheduling configuration
  debug:
    msg: |
      Node scheduling configured:
      - gigabyte: Default node (no taint) - all workloads scheduled here by default
      - beelink: Media-only (tainted) - requires toleration: node.homelab.dev/media-only=true:NoSchedule
      - vhs-vps: Edge-only (tainted) - requires toleration: node.homelab.dev/edge-only=true:NoSchedule
  run_once: true
