---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/infrastructure-config
      version: "*"
      sourceRef:
        kind: GitRepository
        name: homelab
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: cert-manager
    - name: external-secrets
