---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:37.340
              env:
                - name: RENOVATE_GIT_AUTHOR
                  value: "Renovate Bot <bot@renovateapp.com>"
                - name: RENOVATE_REPOSITORIES
                  value: "tonur/homelab"
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-secrets
                      key: RENOVATE_TOKEN
                - name: RENOVATE_GITHUB_COM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-secrets
                      key: RENOVATE_GITHUB_COM_TOKEN
              volumeMounts:
                - name: renovate-cache
                  mountPath: /tmp/renovate
          restartPolicy: OnFailure
          volumes:
            - name: renovate-cache
              emptyDir: {}
