---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: renovate-secrets
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: RENOVATE_TOKEN
