---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: renovate-secrets
    creationPolicy: Owner
    template:
      data:
        RENOVATE_HOST_RULES: |
          [
            {
              "matchHost": "index.docker.io",
              "hostType": "docker",
              "username": "{{`{{ .DOCKER_USER }}`}}",
              "password": "{{`{{ .DOCKER_PASS }}`}}"
            }
          ]
        RENOVATE_TOKEN: "{{`{{ .RENOVATE_TOKEN }}`}}"
        RENOVATE_GITHUB_COM_TOKEN: "{{`{{ .RENOVATE_GITHUB_COM_TOKEN }}`}}"
  data:
    - secretKey: DOCKER_USER
      remoteRef:
        key: DOCKERHUB_USERNAME
    - secretKey: DOCKER_PASS
      remoteRef:
        key: DOCKERHUB_PASSWORD
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: RENOVATE_TOKEN
    - secretKey: RENOVATE_GITHUB_COM_TOKEN
      remoteRef:
        key: RENOVATE_GITHUB_COM_TOKEN
