{{- $defaults := .Values.defaults -}}
{{- range $name, $config := .Values.servers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      securityContext:
        fsGroup: {{ $defaults.pgid }}
        runAsUser: {{ $defaults.puid | int }}
        runAsGroup: {{ $defaults.pgid | int }}

      initContainers:
      # STAGE 1: The "Janitor" - Prepares folders and fixes permissions
      - name: filesystem-prepare
        image: busybox
        securityContext:
          runAsUser: 0 
        command:
        - sh
        - -c
        - |
          echo "Preparing persistent structure..."
          mkdir -p /data/server /data/steam_home
          # Ensure user 50520 owns the whole volume
          chown -R {{ $defaults.puid }}:{{ $defaults.pgid }} /data
        volumeMounts:
        - name: game-storage
          mountPath: /data

      # STAGE 2: The "Provisioner" - Downloads/Updates the game
      - name: steam-updater
        image: {{ $defaults.image }}
        env:
        # Crucial: This tells SteamCMD to put its config files in the PVC
        - name: HOME
          value: "/data/steam_home"
        command: ["/usr/games/steamcmd"]
        args:
          - "+@sSteamCmdForcePlatformType"
          - "windows"
          - "+force_install_dir"
          - "/data/server"
          - "+login"
          - "anonymous"
          - "+app_update"
          - {{ $config.appId | quote }}
          - "validate"
          - "+quit"
        volumeMounts:
        - name: game-storage
          mountPath: /data

      # STAGE 3: The "Server" - Runs the actual game
      containers:
      - name: game-runtime
        image: {{ $defaults.image }}
        env:
        - name: HOME
          value: "/data/steam_home"
        - name: TZ
          value: {{ $defaults.tz | quote }}
        {{- range $config.extraEnvs }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        command:
        - bash
        - -c
        - |
          echo "Starting {{ $name }} Dedicated Server..."
          # exec ensures the game process gets PID 1
          exec xvfb-run --auto-servernum {{ $config.startCommand }}
        volumeMounts:
        - name: game-storage
          mountPath: /data
      volumes:
      - name: game-storage
        persistentVolumeClaim:
          claimName: {{ $name }}-data-pvc
{{- end }}
