{{- $defaults := .Values.defaults -}}
{{- range $name, $config := .Values.servers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      securityContext:
        fsGroup: {{ $defaults.pgid }}
        runAsUser: {{ $defaults.puid | int }}
        runAsGroup: {{ $defaults.pgid | int }}

      initContainers:
      - name: filesystem-prepare
        image: busybox
        securityContext:
          runAsUser: 0 
        command:
        - sh
        - -c
        - |
          echo "Preparing paths and identity..."
          mkdir -p /data/server /data/steam_home /data/etc

          # Create a custom passwd file so the user has a name
          echo "root:x:0:0:root:/root:/bin/sh" > /data/etc/passwd
          echo "steam:x:{{ $defaults.puid }}:{{ $defaults.pgid }}:steam:/data/steam_home:/bin/bash" >> /data/etc/passwd

          chown -R {{ $defaults.puid }}:{{ $defaults.pgid }} /data

          {{- if $config.configInjections }}
          echo "Injecting templated configurations..."
          {{- range $injection := $config.configInjections }}
          {{- range $file := $injection.files }}
          mkdir -p $(dirname {{ $file.destination }})
          rm {{ $file.destination }}
          cp /config-injections/{{ $injection.secretName }}/{{ $file.source }} {{ $file.destination }}
          chown {{ $defaults.puid }}:{{ $defaults.pgid }} {{ $file.destination }}
          echo "{{ $file.destination }} content:"
          cat {{ $file.destination  }}
          {{- end }}
          {{- end }}
          {{- end }}

          echo "Filesystem prepare done!"
        volumeMounts:
        - name: game-storage
          mountPath: /data
        {{- if $config.configInjections }}
        {{- range $injection := $config.configInjections }}
        - name: injection-{{ $injection.secretName }}
          mountPath: /config-injections/{{ $injection.secretName }}
          readOnly: true
        {{- end }}
        {{- end }}

      - name: steam-updater
        image: {{ $defaults.image }}
        env:
        - name: HOME
          value: "/data/steam_home"
        command: ["/bin/bash", "-c"]
        args:
          - |
            # Verify we can actually write to the target before starting
            touch /data/server/write_test && rm /data/server/write_test || (echo "PERMISSIONS FAIL" && exit 1)

            /usr/games/steamcmd \
              +@sSteamCmdForcePlatformType windows \
              +force_install_dir /data/server \
              +login anonymous \
              +app_update {{ $config.appId | quote }} validate \
              +quit
        volumeMounts:
        - name: game-storage
          mountPath: /data
      containers:
      - name: game-runtime
        image: {{ $defaults.image }}
        env:
        - name: USER
          value: "steam"
        - name: HOME
          value: "/data/steam_home"
        - name: TZ
          value: {{ $defaults.tz | quote }}
        - name: WINEDLLOVERRIDES
          value: "mscoree,mshtml="
        {{- range $config.extraEnvs }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        command:
        - bash
        - -c
        - |
          Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99

          until [ -f "{{ $config.binaryPath }}" ]; do
            echo "Waiting for binary..."
            sleep 5
          done

          echo "Starting {{ $name }}..."
          cd /data/server

          {{- if $config.debugCommands }}
          echo "Adding debug commands..."
          {{- $config.debugCommands | nindent 10 }}
          {{- end }}
          
          # Launch the game with Unreal-specific flags
          exec wine "{{ $config.binaryPath }}" {{ $config.binaryFlags }}
        volumeMounts:
        - name: game-storage
          mountPath: /data
      volumes:
      - name: game-storage
        persistentVolumeClaim:
          claimName: {{ $name }}-data-pvc
      {{- if $config.configInjections }}
      {{- range $injection := $config.configInjections }}
      - name: injection-{{ $injection.secretName }}
        secret:
          secretName: {{ $injection.secretName }}
      {{- end }}
      {{- end }}
{{- end }}