---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: game-server-dns
spec:
  endpoints:
  {{- $defaults := .Values.defaults -}}
  {{- range $name, $config := .Values.servers }}
    - dnsName: {{ printf "%s.%s" $name "kragh.dev" }}
      recordType: A
      targets: [ {{ $defaults.publicIP | quote }} ]

    - dnsName: {{ printf "_game._udp.%s.%s" $name "kragh.dev" }}
      recordType: SRV
      targets:
        - {{ printf "0 5 %d %s.%s" (int $config.port) $name "kragh.dev" | quote }}
  {{- end }}