---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: game-server-dns
spec:
  endpoints:
  {{- range $name, $config := .Values.servers }}
  {{- $port := include "game.port" $name }}
    - dnsName: {{ printf "%s.%s" $name "kragh.dev" }}
      recordType: A
      targets: [ {{ $.Values.defaults.publicIP | quote }} ]

    - dnsName: {{ printf "_hl2._udp.%s.%s" $name "kragh.dev" }}
      recordType: SRV
      targets:
        - {{ printf "0 5 %s %s.%s" $port $name "kragh.dev" | quote }}
  {{- end }}