{{- range $name, $config := .Values.servers }}
{{- range $injection := $config.configInjections }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # Unique name for the ExternalSecret resource itself
  name: {{ printf "%s-%s" $name $injection.secretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infiscial
    kind: ClusterSecretStore
  target:
    # This must match the secretName used in your Deployment volumes
    name: {{ $injection.secretName }}
    template:
      engineVersion: v2
      data:
        {{- $injection.secretData | toYaml | nindent 8 }}
  data:
    - secretKey: password
      remoteRef:
        key: gameserver-password
{{- end }}
{{- end }}
