{{- range $name, $config := .Values.servers }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ $name }}-ingress
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app: {{ $name }}
  ingress:
  - from: []
    ports:
    {{- range $config.ports }}
    - protocol: UDP
      port: {{ .targetPort }}
    {{- end }}
{{- end }}