{{- range $name, $config := .Values.servers }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-svc
spec:
  selector:
    app: {{ $name }}
  type: NodePort
  ports:
    - name: game-tcp
      protocol: TCP
      port: 27015
      targetPort: 27015
    - name: game-udp
      protocol: UDP
      port: 27015
      targetPort: 27015
{{- end }}