{{- $defaults := .Values.defaults -}}
{{- range $name, $config := .Values.servers }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-svc
spec:
  type: LoadBalancer
  selector:
    app: {{ $name }}
  ports:
    - name: game-udp
      protocol: UDP
      port: {{ $config.port }}
      targetPort: 27015
    - name: game-tcp
      protocol: TCP
      port: {{ $config.port }}
      targetPort: 27015
{{- end }}