{{- range $name, $config := .Values.servers }}
{{- $port := include "game.port" $name -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-svc
spec:
  type: LoadBalancer
  selector:
    app: {{ $name }}
  ports:
    - name: game-udp
      protocol: UDP
      port: {{ $port }}
      targetPort: 27015
    - name: game-tcp
      protocol: TCP
      port: {{ $port }}
      targetPort: 27015
{{- end }}