apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: traefik
  chart:
    spec:
      chart: traefik
      version: 27.0.x
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Basic deployment configuration
    deployment:
      enabled: true
      kind: Deployment
      replicas: 1
    
    # Node scheduling for edge-only workloads
    nodeSelector:
      node.kubernetes.io/edge: "true"
    tolerations:
      - key: node.homelab.dev/edge-only
        operator: Equal
        value: "true"
        effect: NoSchedule
    
    # Service configuration
    service:
      enabled: true
      type: NodePort
      spec:
        externalTrafficPolicy: Local
        externalIPs:
          - "198.55.102.244"  # VPS public IP
    
    # Port configuration
    ports:
      web:
        port: 80
        exposedPort: 80
        nodePort: 30080
        protocol: TCP
      websecure:
        port: 443
        exposedPort: 443
        nodePort: 30443
        protocol: TCP
        tls:
          enabled: true
    
    # Ingress configuration
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik
    
    # Provider configuration
    providers:
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        allowEmptyServices: false
        ingressClass: traefik
        publishedService:
          enabled: true
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
        allowEmptyServices: false
        allowCrossNamespace: false
    
    # Additional arguments
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.email=contact@kragh.dev"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--log.level=INFO"
      - "--accesslog=true"
    
    # Security context
    securityContext:
      capabilities:
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
    
    # Pod security context
    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: OnRootMismatch
    
    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    # Persistence for ACME certificates
    persistence:
      enabled: true
      size: 128Mi
      path: /data
    
    # Dashboard IngressRoute (disabled for now)
    ingressRoute:
      dashboard:
        enabled: false
    
    # Logs
    logs:
      general:
        level: INFO
      access:
        enabled: true
