apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: traefik
  chart:
    spec:
      chart: traefik
      version: 27.0.x
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    deployment:
      kind: Deployment
      replicas: 1
    nodeSelector:
      node.kubernetes.io/edge: "true"
    tolerations:
      - key: node.kubernetes.io/edge
        operator: Equal
        value: "true"
        effect: NoSchedule
    service:
      enabled: true
      type: NodePort
      spec:
        externalTrafficPolicy: Local
        externalIPs:
          - "198.55.102.244"  # VPS public IP
    ports:
      web:
        port: 80
        exposedPort: 80
        nodePort: 30080
      websecure:
        port: 443
        exposedPort: 443
        nodePort: 30443
    hostNetwork: false
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints: ["websecure"]
        rule: "Host(`traefik.kragh.dev`)"
        tls:
          secretName: traefik-dashboard-tls
    logs:
      general:
        level: INFO
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.email=contact@kragh.dev"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
