apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: traefik
  chart:
    spec:
      chart: traefik
      version: 37.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: NodePort
      spec:
        externalTrafficPolicy: Local
      ports:
        web:
          nodePort: 30080
        websecure:
          nodePort: 30443
    ports:
      web:
        # Preserve real client IP via HAProxy PROXY protocol
        proxyProtocol:
          trustedIPs:
            - 10.172.90.2 # edge gateway WireGuard IP
        forwardedHeaders:
          trustedIPs:
            - 10.172.90.2
      websecure:
        proxyProtocol:
          trustedIPs:
            - 10.172.90.2
        forwardedHeaders:
          trustedIPs:
            - 10.172.90.2
