apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: traefik
  chart:
    spec:
      chart: traefik
      version: 37.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    deployment:
      enabled: true
      kind: Deployment
      replicas: 1

    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 198.55.102.244
        externalTrafficPolicy: Cluster

    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik

    # Minimal providers: rely on chart defaults (CRD + Ingress); no extra args
    providers: {}

    # Keep persistence for ACME certificates (still minimal & practical)
    persistence:
      enabled: true
      size: 128Mi
      storageClass: local-path
