---
- name: Setup VPS edge node
  hosts: edge
  become: true
  vars:
    secrets: "{{ lookup('community.sops.sops', 'secrets/homelab.yaml') | from_yaml }}"
    ansible_become_password: "{{ secrets.gigabyte_password }}"
  vars_files:
    - secrets/homelab.yaml
  tasks:
    - name: Get k3s server hostname from inventory
      set_fact:
        k3s_server_hostname: "gigabyte" # Hardcoded since ansible_become_password is hard coded TODO - figure out a way to get k3s token from gigabyte host without needing password when running on vhs-vps

    - name: Get k3s node token from server
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token_file
      delegate_to: "{{ k3s_server_hostname }}"
      become: true

    - name: Set k3s token fact
      set_fact:
        k3s_node_token: "{{ k3s_token_file.content | b64decode | trim }}"

    - name: Include base role
      include_role:
        name: base
        
    - name: Include tailscale role  
      include_role:
        name: tailscale
        
    - name: Include k3s edge node role
      include_role:
        name: k3s-edge-node
      vars:
        k3s_server_hostname: "{{ k3s_server_hostname }}"
        k3s_token: "{{ k3s_node_token }}"
