---
# This playbook finishes the k3s reconfiguration
- name: Finish k3s configuration - node scheduling and GitOps
  hosts: k3s_server
  become: true
  vars:
    secrets: "{{ lookup('community.sops.sops', 'secrets/homelab.yaml') | from_yaml }}"
    ansible_become_password: "{{ secrets.ansible_become_password }}"
    bw_access_token: "{{ secrets.bw_access_token }}"
  roles:
    - k3s-node-scheduling
    - gitops-bootstrap
