---
- name: Base setup and Tailscale mesh networking
  hosts: all
  become: true
  tags: [initial, base, tailscale]
  roles:
    - { role: base, tags: [initial, base] }
    - { role: tailscale, tags: [initial, tailscale] }

- name: Configure edge gateway
  hosts: edge
  become: true
  tags: [wireguard, edge, gateway]
  vars:
    edge_gateway_wg_private_key: "{{ (lookup('community.sops.sops', 'secrets/homelab.yaml') | from_yaml)['edge_gateway_wg_private_key'] }}"
  roles:
    - { role: edge_gateway, tags: [wireguard, edge, gateway] }

- name: k3s control plane
  hosts: k3s_server
  become: true
  tags: [k3s, control-plane, wireguard]
  vars:
    control_plane_wg_private_key: "{{ (lookup('community.sops.sops', 'secrets/homelab.yaml') | from_yaml)['control_plane_wg_private_key'] }}"
  roles:
    - { role: k3s-control-plane, tags: [k3s, control-plane] }
    - { role: wireguard_peer, tags: [wireguard, wgpeer] }

- name: k3s worker nodes
  hosts: k3s_agents
  become: true
  tags: [k3s, workers]
  roles:
    - { role: k3s-worker-nodes, tags: [k3s, workers] }

- name: Bootstrap GitOps infrastructure
  hosts: k3s_server
  become: true
  tags: [gitops, flux]
  roles:
    - { role: gitops-bootstrap, tags: [gitops, flux] }
