apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: open-webui
spec:
  secretName: open-webui-tls
  dnsNames:
    - open-webui.kragh.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
