---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-webui-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: open-webui-secrets
    creationPolicy: Owner
  data:
    - secretKey: OLLAMA_API_KEY
      remoteRef:
        key: OLLAMA_API_KEY
