---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui
annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: open-webui.kragh.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-webui 
                port:
                  number: 8080
  tls:
    - hosts:
        - open-webui.kragh.dev
      secretName: open-webui-tls
