---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  namespace: open-webui
  labels:
    app.kubernetes.io/name: open-webui
  annotations:
    helm.sh/resource-policy: keep
spec:
  volumeName: open-webui-data-pvc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
