---
apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: open-webui
stringData:
    OLLAMA_API_KEY: ENC[AES256_GCM,data:y3VsOHRlLhpuhT+qyj/jf0BW3A7Z3Ul5SwxE1gAMdpSWj+r0V2/BkVHdphf73cuMurR+KbwV2JDW,iv:mMXZpwsP4fHGZvdlrOtQIP1r2fmNKdvVzqyx8DcG4XI=,tag:F+IHKYUVDXcc7lae1pp+tQ==,type:str]
sops:
    age:
        - recipient: age19cjycc6l8pnjxgmclp7jzfd6kx79v2w3vrn3y9xzhd2hkfmyvvls6jk3v7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcmdpM3dPTktWUzRlcXFI
            WUZmYWVud1JJMU1HaWF0SUcxQVcyWlljZ1dNCkFPZm55UkxlbWM2WHc1NUoySDg0
            N0kzMWJsakpUZ2NTbGMwdmUwSzVXdzQKLS0tIDNoU3hFMDZyaXQrSEpzY2p5RUJG
            S0tjakVyRTBGa3MxRmRhSzBBUVdKNUEKvukbubK/fN6pdK1wA/8fmEakTy8rS6Tv
            gywOhnA0jqtgmxgR3ZNWSVNHK84HKGDai86//KvsNKXvXgIbzy8pnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T00:36:41Z"
    mac: ENC[AES256_GCM,data:NwXPvlA3QesS380ZHG1pFtlId9yJuDINn92Y/+ou9eTtYzr4Zjo6I9JmqxygIfAp7OvF+H60I989g2w5vrWaZaLx1WlBRp5v10NbGU0En4JZcPaaD31Ju9/rWI8N4MhSJvUKDzBNXwGaFQ0lE9jqMoxneBvWr9uLw2WnmfCw6PI=,iv:yJPXECpVggRvLov60qGuDJkKSJQAsM1ehiaAdA7Je4A=,tag:0D4YQMDUkPY44ySwjUOZ8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
