---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dex
  namespace: infrastructure
spec:
  interval: 24h
  url: https://charts.dexidp.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
  namespace: infrastructure
spec:
  interval: 15m
  releaseName: dex
  targetNamespace: dex
  chart:
    spec:
      chart: dex
      version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: infrastructure
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  dependsOn:
    - name: infrastructure-dex-config
  values:
    ingress:
      enabled: true
      # Use your IngressClass (Traefik) and annotations
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: dex.kragh.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: dex-tls
          hosts:
            - dex.kragh.dev

    # Use external secret for configuration
    configSecret:
      create: false
      name: dex-github-oauth
