---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infrastructure-dex-config
  namespace: infrastructure
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/infrastructure-dex-config
      version: "*"
      sourceRef:
        kind: GitRepository
        name: homelab
        namespace: default
      interval: 5m
      reconcileStrategy: Revision # Local chart
  install:
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  dependsOn:
    - name: infrastructure-external-secrets-config
