---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: infrastructure
spec:
  interval: 24h
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: infrastructure
spec:
  interval: 15m
  releaseName: oauth2-proxy
  targetNamespace: infrastructure
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.10.3" 
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: infrastructure
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml
    config:
      clientID: "357890574222860083"
      configFile: |-
        providers = "oidc"
        
        # Zitadel OIDC Configuration
        oidc_issuer_url = "https://homelab-wzcnuv.us1.zitadel.cloud"

        # Cookie configuration
        cookie_domains = ".kragh.dev"
        cookie_secure = true
        cookie_httponly = true


        redirect_url = "https://oauth2-proxy.kragh.dev/oauth2/callback"
        whitelist_domains = ".kragh.dev"

        # Email validation
        email_domains = ["*"]
    
    # Use existing secret created by External Secrets
    existingSecret: oauth2-proxy-secrets
    existingSecretPerKey: false
    
    ingress:
      enabled: true
      className: traefik
      path: /
      pathType: Prefix
      hosts:
        - oidc.kragh.dev
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - secretName: oidc-kragh-dev-tls
          hosts:
            - oidc.kragh.dev
