---
apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: infrastructure
stringData:
    client-id: ENC[AES256_GCM,data:vlYVyNHG9yB+Xyk4lp7LX6T+,iv:0MwWtfGQ1NhEJU+6DuySB8oljWVyMub3iMIkQBim8rE=,tag:ieA7Cc3xtGvWyrZ2Gdyk1A==,type:int]
    client-secret: ENC[AES256_GCM,data:I7TX3RIex6XtNDzzK/e2O0x+mJeZeIadff0E+1hHI7r3xL3CY8AmEwPan9JbO5Q1HLS9RfrggmLShL5kh+NY8A==,iv:diIUyZHJh4SLEQTlTnHMGTbGSE+8DZTWNtm3dYW46W8=,tag:gZeh1rEmZaf/DwSb9c5WlA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:tFUt8mfkWmh//qD9cHHkEhM2KT+JUs1ENN3UCZ5zDH0=,iv:BmPlc1Pmnh9Fk8UK2ZPte1Z7RVZBMpwPh3U9Y9hL1D4=,tag:G/xRj7WZqyaukU1RUdWW7w==,type:str]
sops:
    age:
        - recipient: age19cjycc6l8pnjxgmclp7jzfd6kx79v2w3vrn3y9xzhd2hkfmyvvls6jk3v7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMlF2VGM0WktQeWJiL0Ns
            aXRFRUZMSm1NMWR4cDNiRFFaSiszOUxFbTFRClJWN3FFRE00K2RkUEhrQmdHUnJJ
            NFI3MzBjZ1hNZWZRZlUvVG5MaW1RalkKLS0tIERXNVVScjZsWWNVSktlZWdyYi9i
            Y0pPRWI3N28wTGxwcFpXd25xNS9uUEEKKXmbGTg1+ZTT8MRBrJhzvizKlQvgAuke
            AlePBVAb6hXj2T9TKTPxj14+G3CLfWBg/i6hwL8mhbDPxw1nwbAl9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T00:06:50Z"
    mac: ENC[AES256_GCM,data:+AlrYd/p91WXoHrb7HQMMc8n+gBN49xxbw9Q8OjdbwdTUOlXKFaqoyoM0fFtUwLDvim/qSjjD75yUNyHtABJp4bsIP4S2/mSIwn1dT40WxoJNgJ7ia9ijAEYbFZoprg+MZ66bqABQeHoUHy+Zh89hD4Gpw7SAqQHU0wT22JEAVQ=,iv:QqXuY2SfaCF3zR1Ri2nLn91T9m6TTwOk2to72kpXq68=,tag:Q0Fpf/VuvO89o7es637rHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
