apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: infrastructure
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: ZITADEL_OAUTH2_PROXY_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: ZITADEL_OAUTH2_PROXY_CLIENT_SECRET
    - secretKey: cookie-secret
      remoteRef:
        key: OAUTH2_PROXY_COOKIE_SECRET