---
apiVersion: batch/v1
kind: Job
metadata:
  name: infrastructure-readiness-check-{{ .Release.Revision }}
  namespace: infrastructure
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: readiness-check
        image: alpine/k8s:1.33.4
        command: ["/bin/sh", "-c"]
        args:
        - |
          release_name="{{ .Release.Name }}"
          interval=10

          child_hr_ready() {
            if kubectl wait --for=condition=Ready helmrelease "$name" -n "$namespace" --timeout=100s; then
              return 0
            else
              return 1
            fi
          }

          helm_release=$(kubectl get helmrelease -A -l "helm.toolkit.fluxcd.io/name=$release_name" -o jsonpath='{range .items[*]}{.metadata.namespace}/{.metadata.name}{"\n"}{end}')

          for helm_release in $helm_release; do
            namespace=$(echo "$helm_release" | cut -d'/' -f1)
            name=$(echo "$helm_release" | cut -d'/' -f2)

            until child_hr_ready; do
              echo "Child HelmRelease $name is not ready, retrying in $interval seconds.."
              sleep $interval
            done

          done

          echo "All child HelmReleases are ready."