---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mogenius
  namespace: infrastructure
spec:
  interval: 24h
  url: https://helm.mogenius.com/public
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
  namespace: infrastructure
spec:
  interval: 5m
  chart:
    spec:
      chart: renovate-operator
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: mogenius
        namespace: infrastructure
      interval: 1m
      reconcileStrategy: Revision
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    extraEnv:
      - name: RENOVATE_PLATFORM
        value: "forgejo"
      - name: RENOVATE_ENDPOINT
        value: "https://codeberg.org/api/v1"
      - name: RENOVATE_TOKEN
        valueFrom:
          secretKeyRef:
            name: renovate-secrets
            key: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: renovate-secrets
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: RENOVATE_TOKEN
