---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tailscale
  namespace: infrastructure
spec:
  interval: 24h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: infrastructure
spec:
  interval: 15m
  releaseName: tailscale-operator
  targetNamespace: tailscale
  chart:
    spec:
      chart: tailscale-operator
      version: "1.78.3"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: infrastructure
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: infrastructure-tailscale-operator-config
      namespace: infrastructure
  values:
    # Resource settings
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    
    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
    
    # Enable RBAC
    rbac:
      create: true
    
    # Service account
    serviceAccount:
      create: true
      name: tailscale-operator
      annotations: {}
    
    # Enable ingress certificate provisioning
    operatorConfig:
      defaultTags:
        - "k8s-operator"
        - "homelab"
