---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/homelab/infrastructure/cert-manager-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  dependsOn:
    - name: infrastructure-cert-manager
  timeout: 5m
  wait: true
