---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-external-dns
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/homelab/infrastructure/external-dns"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  timeout: 5m
  wait: true
  dependsOn:
    - name: infrastructure-external-secrets-config
