defaults:
  platform: "linux"
  publicIP: 198.55.102.244
  image: thetestgame/steam:stable
  tz: "Europe/Copenhagen"
  puid: "50520"
  pgid: "50520"
  storageClass: "local-path"
  storageSize: "20Gi"

servers:
  windrose:
    platform: "windows"
    appId: "4129620"
    ports:
      - name: game-udp
        port: 27099
        targetPort: 27099
        protocol: UDP
      - name: game-tcp
        port: 27099
        targetPort: 27099
        protocol: TCP
    binaryPath: "/data/server/R5/Binaries/Win64/WindroseServer-Win64-Shipping.exe"
    binaryFlags: "-server -log -unattended -NoUI -port=27099 -PublicIP=198.55.102.244 -MultiHome -BLPort=27098"
    extraEnvs:
      - name: CURL_IPRESOLVE
        value: "v4"
      - name: UE_FORCE_IPV4
        value: "1"
      - name: WINEDEBUG
        value: "-all,warn+winsock"
      - name: WINEESYNC
        value: "1"
      - name: WINEIPVERSION
        value: "ipv4"
      - name: WINEDLLOVERRIDES
        value: "mscoree,mshtml=,bcrypt=n,crypt32=n,ws2_32=n"
    debugCommands: |
      tail -F /data/server/R5/Saved/Logs/*.log &
    configInjections:
      - secretName: "windrose-json-config"
        files:
          - source: "ServerDescription.json"
            destination: "/data/server/R5/ServerDescription.json"
        secretData:
          # We template the entire JSON file here
          ServerDescription.json: |
            {
              "Version": 1,
              "DeploymentId": "0.10.0.4.268-9d2ca277",
              "ServerDescription_Persistent": {
                "PersistentServerId": "288F0FDE426E0671BDF607818598539F",
                "InviteCode": "mnaXiwCij5xZ3ZgXGj1hUWHPbtqK4jih",
                "IsPasswordProtected": {{ if .password }}true{{ else }}false{{ end }},
                "Password": {{ .password | quote }},
                "ServerName": "Tonur",
                "WorldIslandId": "48F07DE8E24049BAE7A77B2EF4A61345",
                "MaxPlayerCount": 8,
                "UserSelectedRegion": "",
                "P2pProxyAddress": "0.0.0.0"
              }
            }