---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/homelab/infrastructure/external-secrets-config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  dependsOn:
    - name: homelab-cluster
  # Wait for ESO HelmRelease to be ready before applying ClusterSecretStore
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: external-secrets
      namespace: external-secrets
