---
# CoreDNS Deployment Patch - Adds volume mount for custom configuration
# This patches the existing CoreDNS deployment to mount custom configs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/component: dns
    k8s-app: kube-dns
spec:
  template:
    spec:
      containers:
      - name: coredns
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        - name: custom-config-volume
          mountPath: /etc/coredns/custom
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: coredns
          items:
          - key: Corefile
            path: Corefile
          - key: NodeHosts
            path: NodeHosts
      - name: custom-config-volume
        configMap:
          name: coredns-custom
          items:
          - key: kragh.dev.server
            path: kragh.dev.server