---
# Simple CoreDNS replacement with basic kragh.dev zone
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/component: dns
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . 1.1.1.1 8.8.8.8 {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
    
    # Authoritative DNS server for kragh.dev domain
    kragh.dev {
        errors
        ready
        log
        
        # Enable AXFR zone transfers for secondary servers
        transfer {
            to *
        }
        
        # Complete authoritative zone data for kragh.dev
        file /etc/coredns/zones/kragh.dev.zone kragh.dev {
            reload 30s
        }
    }