---
# Enhanced external service for authoritative DNS with UDP and TCP support
apiVersion: v1
kind: Service
metadata:
  name: coredns-external
  namespace: kube-system
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/component: dns-external
spec:
  type: NodePort
  ports:
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
    nodePort: 31053
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
    nodePort: 31054
  selector:
    k8s-app: kube-dns
