---
# NodePort Service to expose the built-in CoreDNS on port 31053
# This reuses the existing CoreDNS deployment with custom configuration
apiVersion: v1
kind: Service
metadata:
  name: coredns-external
  namespace: kube-system
  labels:
    app.kubernetes.io/name: coredns-external
    app.kubernetes.io/component: dns
spec:
  type: NodePort
  selector:
    k8s-app: kube-dns  # Select the built-in CoreDNS deployment
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 31053
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 31053
  # Ensure external traffic can reach this
  externalTrafficPolicy: Local
