---
# Simple CoreDNS replacement with basic kragh.dev zone
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/component: dns
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . 1.1.1.1 8.8.8.8 {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
    
    # Internal cluster DNS for kragh.dev services
    # This provides internal resolution for cluster services
    # External DNS queries should still go to Hetzner DNS
    kragh.dev {
        errors
        ready
        log
        
        # Internal cluster services - these IPs are for internal access
        hosts {
            # Internal cluster service IPs
            10.43.0.100 json-resume.kragh.dev  # Example internal service IP
            10.43.0.101 api.kragh.dev          # Example internal service IP
            10.43.0.102 home.kragh.dev         # Example internal service IP
            
            # For external services, fall through to upstream DNS
            fallthrough
        }
        
        # Forward kragh.dev queries to upstream DNS (Hetzner) if not found locally
        forward . 1.1.1.1 8.8.8.8
    }