apiVersion: v1
kind: Secret
metadata:
    name: desec-token
    namespace: external-dns
stringData:
    token: ENC[AES256_GCM,data:oFHyXb9nQIgmu/cXAZqCtHM7feKkAYZnOQFiig==,iv:UfWRElwsEYvBrfrcAuAV+I1dg44BCSeixWQwq5jOZAo=,tag:qGduefzMe7CuEb8BxXSzAQ==,type:str]
sops:
    age:
        - recipient: age19cjycc6l8pnjxgmclp7jzfd6kx79v2w3vrn3y9xzhd2hkfmyvvls6jk3v7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNlAvV1hMY3cxdkovbzYy
            OXZQVU9PbWNITExTSVhaVTFGRkIyRHJ3elNRCjVMTjNvc2xxN2paZmhWQ2FwUHl4
            WkwvVGRUdGtzd3dJKzRDUzVsMEVwN28KLS0tIG13M1d2TGNVcm02aVM2S3BhZ0Y0
            UXROcCs1QlUxclZHdUxOMVRrcXlZaUEKeOLdespk4QFa70aOcbzzUhwwSFk7czyC
            5CqRSVAq1JR0d6S51GC1XK5SGRlFpBA3U0ouWkKetlydwcLp+ejxEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T23:58:40Z"
    mac: ENC[AES256_GCM,data:GATs/EILZztLDjYHkQJZ54B36RizSqJDOt0LqGC4w/Yd6St19hE47zeT6AmWdYTTLQX2eARJbtUh9YN9lcq6BVgQN8zoJ8najjJVxcP7W7AodByquRWgt/BRohfY0xnmt+V9vpZKeJsQpU8Szfs8aA2/WqnbE9vSzAToML+UvJo=,iv:soB5m+LgVR4+mjRE0HC6zW+yVo/TKtSdamBxhZQlW2o=,tag:ptUJ+703nAQgUqF+miXEkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
