---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hetzner-dns-token
  namespace: external-dns
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: hetzner-dns-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: hetzner-dns-token
