---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-external
  namespace: kube-system
spec:
  gatewayClassName: traefik
  listeners:
    - name: tls
      protocol: TLS
      port: 443
      hostname: "kube.kragh.dev"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: kubeapi-tlsroute
  namespace: default
spec:
  hostnames:
    - "kube.kragh.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: kubernetes
          namespace: default
          port: 6443
