---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kubeapi
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`kube.kragh.dev`)
      services:
        - name: kubernetes
          port: 6443
  tls:
    passthrough: true
