apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: public-ip-vpn
  namespace: infrastructure
spec:
  endpoints:
    - dnsName: "*.kragh.dev"
      recordType: A
      targets: [ "198.55.102.244" ]
      ttl: 3600
