---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  namespace: infrastructure
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: renovate-secrets
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: RENOVATE_TOKEN
---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: homelab-updates
  namespace: infrastructure
spec:
  image: renovate/renovate:37.340
  schedule: "52 21 * * *"
  parallelism: 1 
  provider:
    name: "gitea" 
    endpoint: "https://codeberg.org/api/v1"

  extraEnv:
    - name: RENOVATE_TOKEN
      valueFrom:
        secretKeyRef:
          name: renovate-secrets
          key: RENOVATE_TOKEN
    - name: RENOVATE_AUTODISCOVER
      value: "true"
    - name: RENOVATE_AUTODISCOVER_FILTER
      value: "tonur/*"

  # This uses the default /tmp mount as defined in your CRD's default properties
  scratchVolume:
    enabled: true
    path: "/tmp"
