---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-tailscale
  namespace: traefik
  annotations:
    tailscale.com/hostname: homelab
spec:
  ingressClassName: tailscale
  rules:
    - host: homelab.pirate-acrux.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik
                port:
                  number: 443
  tls:
    - hosts:
        - homelab.pirate-acrux.ts.net
