---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-tailscale
  namespace: traefik
  annotations:
    tailscale.com/hostname: homelab
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: traefik
      port:
        number: 80
  tls:
    - hosts:
        - homelab.pirate-acrux.ts.net